version: '3.8'

services:

  api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - DEBUG=${DEBUG}
      - MODEL_PATH=${MODEL_PATH}
      - DATA_DIR=${DATA_DIR}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: uvicorn app:app --host ${API_HOST} --port ${API_PORT} --reload

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - PORT=${PORT}
    env_file:
      - .env
    depends_on:
      - api

  dev:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - DEBUG=${DEBUG}
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: tail -f /dev/null